---

- name: add docker apt key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: add docker apt repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present update_cache=yes

- name: install docker and requirements
  apt: pkg={{item}} state=present
  with_items:
    - apparmor
    - docker-engine

- name: configure docker
  copy: content='DOCKER_OPTS=""' dest=/etc/default/docker

- name: allow vagrant user to run docker commands without sudo
  user: name=vagrant append=yes groups=docker

- name: install required python packages for ansible and docker
  apt: pkg={{item}} state=latest update_cache=yes force=true
  with_items:
    - python-pip
    - python-dev

- name: install the version of docker-py used by ansible
  pip: name=docker-py version=1.1.0

- name: build docker images from dockerfiles.
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    path: "/vagrant/provisioning/{{ item.directory }}"
    state: build
  with_items:
    - { name: data, tag: "data", directory: data }
    - { name: db, tag: "mysql", directory: db }
    - { name: server, tag: "server", directory: server }

- name: create data volume
  docker:
    image: data:data
    name: data
    state: present

- name: run a mysql container.
  docker:
    image: db:mysql
    name: db
    state: reloaded
    volumes_from: data
    ports: "3306:3306"

- name: run a server container.
  docker:
    image: server:server
    name: server
    state: reloaded
    ports: "80:80"
